#!/usr/bin/env bash
# One-shot installer for pgp-sync on a Debian/Ubuntu box (tested on
# Debian 13 / systemd 257). Idempotent — safe to re-run after upgrades.
#
# Configuration comes from <repo>/.env (or .env.example as fallback). Copy
# .env.example to .env and edit before running.
#
# Run from inside this repo on the target host:
#   sudo ./scripts/install.sh
#
# Expects a freshly-built binary at ./bin/pgp-sync-linux-amd64. The
# build-linux.sh script cross-compiles one from a Go toolchain.

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "Run as root (sudo $0)" >&2
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# --- load deploy-time config -------------------------------------------------
# Order of precedence: existing env > .env > .env.example. We `set -a` so any
# variable defined in the file becomes exported into our shell.
set -a
if [[ -f "$REPO_ROOT/.env" ]]; then
  # shellcheck disable=SC1091
  source "$REPO_ROOT/.env"
elif [[ -f "$REPO_ROOT/.env.example" ]]; then
  # shellcheck disable=SC1091
  source "$REPO_ROOT/.env.example"
fi
set +a

DOMAIN="${DOMAIN:-sync.example.com}"
PORT="${PORT:-8443}"
DATA_DIR="${DATA_DIR:-/var/lib/pgp-sync}"
CERT_DIR="${CERT_DIR:-/etc/pgp-sync/certs}"
SERVICE_USER="${SERVICE_USER:-pgpsync}"

BIN_SRC="${BIN_SRC:-$REPO_ROOT/bin/pgp-sync-linux-amd64}"
if [[ ! -x "$BIN_SRC" ]]; then
  echo "Missing binary: $BIN_SRC" >&2
  echo "Build it first with: ./scripts/build-linux.sh" >&2
  exit 1
fi

# --- system user -------------------------------------------------------------
if ! id -u "$SERVICE_USER" >/dev/null 2>&1; then
  echo "==> creating $SERVICE_USER user"
  useradd --system --no-create-home --shell /usr/sbin/nologin "$SERVICE_USER"
fi

# --- directories -------------------------------------------------------------
install -d -m 0755 -o root           -g root           /opt/pgp-sync
install -d -m 0755 -o root           -g root           /etc/pgp-sync
install -d -m 0750 -o "$SERVICE_USER" -g "$SERVICE_USER" "$CERT_DIR"
install -d -m 0750 -o "$SERVICE_USER" -g "$SERVICE_USER" "$DATA_DIR"

# --- binary ------------------------------------------------------------------
install -m 0755 "$BIN_SRC" /opt/pgp-sync/pgp-sync

# --- systemd unit ------------------------------------------------------------
# We render this from the .service template so the User= matches the
# configured SERVICE_USER and ReadWritePaths= matches DATA_DIR.
cat > /etc/systemd/system/pgp-sync.service <<UNIT
[Unit]
Description=pgp-sync — end-to-end encrypted PGP keyring sync server
After=network.target

[Service]
Type=simple
User=$SERVICE_USER
Group=$SERVICE_USER
EnvironmentFile=/etc/pgp-sync/env
ExecStart=/opt/pgp-sync/pgp-sync
Restart=on-failure
RestartSec=2

NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true
ReadWritePaths=$DATA_DIR
ReadOnlyPaths=/etc/pgp-sync /opt/pgp-sync

StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
UNIT
chmod 0644 /etc/systemd/system/pgp-sync.service

# --- runtime env -------------------------------------------------------------
# Generated from .env. Re-runs of the installer regenerate this — the values
# in .env are the source of truth.
cat > /etc/pgp-sync/env <<RUNTIME_ENV
# Auto-generated by scripts/install.sh from $REPO_ROOT/.env
PGP_SYNC_ADDR=:$PORT
PGP_SYNC_DB=$DATA_DIR/data.db
PGP_SYNC_CERT=$CERT_DIR/fullchain.pem
PGP_SYNC_KEY=$CERT_DIR/privkey.pem
RUNTIME_ENV
chmod 0644 /etc/pgp-sync/env

# --- start -------------------------------------------------------------------
systemctl daemon-reload
systemctl enable pgp-sync.service
systemctl restart pgp-sync.service

cat <<EOF

==> pgp-sync installed.
    domain:    $DOMAIN
    port:      $PORT
    data:      $DATA_DIR
    certs:     $CERT_DIR
    user:      $SERVICE_USER

    status: systemctl status pgp-sync
    logs:   journalctl -u pgp-sync -f

Next: wire up TLS via acme.sh:
    ~/.acme.sh/acme.sh --deploy -d $DOMAIN --deploy-hook $REPO_ROOT/deploy/acme-deploy-hook.sh

EOF
